#!/usr/bin/env node
var fs = require('fs');
var util = require('util');
var cmark = require('./cmark');

file = process.argv[2] || '/dev/stdin';

fs.readFile(file, 'utf8', function(err, data) {
  if (err) {
    return console.log(err);
  }
  var parser   = new cmark.DocParser();
  var renderer = new cmark.HtmlRenderer();
  process.stdout.write(renderer.render(parser.parse(data)));
});
